### ISSUE TITLE
.rtl.css (or --ext value) files must be excluded

### ISSUE THREAD

**Issue by smmoosavi** [MohammadYounes/rtlcss#90] opened 2017-01-22 19:18 UTC
```
$ mkdir styles
$ touch styles/a.css
$ touch styles/b.css
$ ls styles/
a.css  b.css

$ 
$ rtlcss -d styles/
$ ls styles
a.css  a.rtl.css  b.css  b.rtl.css

$ rtlcss -d styles/
$ ls styles/
a.css  a.rtl.css  a.rtl.rtl.css  b.css  b.rtl.css  b.rtl.rtl.css

```

**Comment by MohammadYounes** [comment] 2017-01-22 19:22
This is a duplicate of #64, for the time being you can set the destination to a different folder as mentioned [here](https://github.com/MohammadYounes/rtlcss/issues/64#issuecomment-206780739)

**Closed by MohammadYounes** 2017-01-22 19:22 UTC
Labels: duplicate
